' ***^^^***|||***^^^***' ' ' ' %%%###%%%eb654850d424fa1543b29ed22b212664%%%###%%%' ***^^^***|||***^^^***'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports Fred2 = System

Namespace CodeDOMTest
    
    Public Class Startup
        
        Public Shared Sub Main()
            Dim iSum As Integer
            Dim iValue As Integer = 42
            Dim stream As System.IO.Stream
            Dim fileName As String = "Test.txt"
            System.Console.WriteLine("Hello World")
            iSum = (42 + 23)
            stream = New System.IO.FileStream(fileName, System.IO.FileMode.Create)
            Dim aInts() As Integer
            Dim a2Ints() As Integer
            a2Ints = New Integer(9) {}
            aInts = New Integer() {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
            iValue = aInts(3)
            Dim i As Integer = 0
            aInts(i) = aInts((i + 1))
            If (i > 6) Then
                System.Console.WriteLine("True Executed")
            Else
                System.Console.WriteLine("False Executed")
            End If
            i = 0
            Do While (i <= 9)
                System.Console.WriteLine(aInts(i))
                i = (i + 1)
            Loop
            obj.MethodA(obj.MethodC(j))
            Startup.EqualityDifference
        End Sub
        
        Shared Sub EqualityDifference()
            Dim iValue As Integer
            If (iValue  _
                        = (42 + 23)) Then
                System.Console.WriteLine("True Executed")
            Else
                System.Console.WriteLine("False Executed")
            End If
        End Sub
    End Class
End Namespace
