' ***^^^***|||***^^^***' ' ' ' %%%###%%%61900171cc86657dad276c7e79c2158c%%%###%%%' ***^^^***|||***^^^***//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace CodeDOMTest {
    using Fred2 = System;
    
    
    public class Startup {
        
        public static void Main() {
            int iSum;
            int iValue = 42;
            System.IO.Stream stream;
            string fileName = "Test.txt";
            System.Console.WriteLine("Hello World");
            iSum = (42 + 23);
            stream = new System.IO.FileStream(fileName, System.IO.FileMode.Create);
            int[] aInts;
            int[] a2Ints;
            a2Ints = new int[10];
            aInts = new int[] {
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9};
            iValue = aInts[3];
            int i = 0;
            aInts[i] = aInts[(i + 1)];
            if ((i > 6)) {
                System.Console.WriteLine("True Executed");
            }
            else {
                System.Console.WriteLine("False Executed");
            }
            for (i = 0; (i <= 9); i = (i + 1)) {
                System.Console.WriteLine(aInts[i]);
            }
            obj.MethodA(obj.MethodC(j));
            Startup.EqualityDifference();
        }
        
        static void EqualityDifference() {
            int iValue;
            if ((iValue 
                        = (42 + 23))) {
                System.Console.WriteLine("True Executed");
            }
            else {
                System.Console.WriteLine("False Executed");
            }
        }
    }
}
