'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace ClassViaCodeDOM
    
    Public Class Customers
        
        Private m_CustomerID As [String]
        
        Private m_CompanyName As [String]
        
        Private m_ContactName As [String]
        
        Private m_ContactTitle As [String]
        
        Private m_Address As [String]
        
        Private m_City As [String]
        
        Private m_Region As [String]
        
        Private m_PostalCode As [String]
        
        Private m_Country As [String]
        
        Private m_Phone As [String]
        
        Private m_Fax As [String]
        
        Public Overridable Property CustomerID As [String]
            Get
                Return Me.m_CustomerID
            End Get
            Set
                Me.m_CustomerID = value
            End Set
        End Property
        
        Public Overridable Property CompanyName As [String]
            Get
                Return Me.m_CompanyName
            End Get
            Set
                Me.m_CompanyName = value
            End Set
        End Property
        
        Public Overridable Property ContactName As [String]
            Get
                Return Me.m_ContactName
            End Get
            Set
                Me.m_ContactName = value
            End Set
        End Property
        
        Public Overridable Property ContactTitle As [String]
            Get
                Return Me.m_ContactTitle
            End Get
            Set
                Me.m_ContactTitle = value
            End Set
        End Property
        
        Public Overridable Property Address As [String]
            Get
                Return Me.m_Address
            End Get
            Set
                Me.m_Address = value
            End Set
        End Property
        
        Public Overridable Property City As [String]
            Get
                Return Me.m_City
            End Get
            Set
                Me.m_City = value
            End Set
        End Property
        
        Public Overridable Property [Region] As [String]
            Get
                Return Me.m_Region
            End Get
            Set
                Me.m_Region = value
            End Set
        End Property
        
        Public Overridable Property PostalCode As [String]
            Get
                Return Me.m_PostalCode
            End Get
            Set
                Me.m_PostalCode = value
            End Set
        End Property
        
        Public Overridable Property Country As [String]
            Get
                Return Me.m_Country
            End Get
            Set
                Me.m_Country = value
            End Set
        End Property
        
        Public Overridable Property Phone As [String]
            Get
                Return Me.m_Phone
            End Get
            Set
                Me.m_Phone = value
            End Set
        End Property
        
        Public Overridable Property Fax As [String]
            Get
                Return Me.m_Fax
            End Get
            Set
                Me.m_Fax = value
            End Set
        End Property
    End Class
End Namespace
