//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace ClassViaCodeDOM
{
    using System;
    
    
    public class Customers
    {
        
        private String m_CustomerID;
        
        private String m_CompanyName;
        
        private String m_ContactName;
        
        private String m_ContactTitle;
        
        private String m_Address;
        
        private String m_City;
        
        private String m_Region;
        
        private String m_PostalCode;
        
        private String m_Country;
        
        private String m_Phone;
        
        private String m_Fax;
        
        public virtual String CustomerID
        {
            get
            {
                return this.m_CustomerID;
            }
            set
            {
                this.m_CustomerID = value;
            }
        }
        
        public virtual String CompanyName
        {
            get
            {
                return this.m_CompanyName;
            }
            set
            {
                this.m_CompanyName = value;
            }
        }
        
        public virtual String ContactName
        {
            get
            {
                return this.m_ContactName;
            }
            set
            {
                this.m_ContactName = value;
            }
        }
        
        public virtual String ContactTitle
        {
            get
            {
                return this.m_ContactTitle;
            }
            set
            {
                this.m_ContactTitle = value;
            }
        }
        
        public virtual String Address
        {
            get
            {
                return this.m_Address;
            }
            set
            {
                this.m_Address = value;
            }
        }
        
        public virtual String City
        {
            get
            {
                return this.m_City;
            }
            set
            {
                this.m_City = value;
            }
        }
        
        public virtual String Region
        {
            get
            {
                return this.m_Region;
            }
            set
            {
                this.m_Region = value;
            }
        }
        
        public virtual String PostalCode
        {
            get
            {
                return this.m_PostalCode;
            }
            set
            {
                this.m_PostalCode = value;
            }
        }
        
        public virtual String Country
        {
            get
            {
                return this.m_Country;
            }
            set
            {
                this.m_Country = value;
            }
        }
        
        public virtual String Phone
        {
            get
            {
                return this.m_Phone;
            }
            set
            {
                this.m_Phone = value;
            }
        }
        
        public virtual String Fax
        {
            get
            {
                return this.m_Fax;
            }
            set
            {
                this.m_Fax = value;
            }
        }
    }
}
