//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace ClassViaCodeDOM
{
    using System;
    
    
    public class Orders
    {
        
        private Int32 m_OrderID;
        
        private String m_CustomerID;
        
        private Int32 m_EmployeeID;
        
        private DateTime m_OrderDate;
        
        private DateTime m_RequiredDate;
        
        private DateTime m_ShippedDate;
        
        private Int32 m_ShipVia;
        
        private Decimal m_Freight;
        
        private String m_ShipName;
        
        private String m_ShipAddress;
        
        private String m_ShipCity;
        
        private String m_ShipRegion;
        
        private String m_ShipPostalCode;
        
        private String m_ShipCountry;
        
        public virtual Int32 OrderID
        {
            get
            {
                return this.m_OrderID;
            }
            set
            {
                this.m_OrderID = value;
            }
        }
        
        public virtual String CustomerID
        {
            get
            {
                return this.m_CustomerID;
            }
            set
            {
                this.m_CustomerID = value;
            }
        }
        
        public virtual Int32 EmployeeID
        {
            get
            {
                return this.m_EmployeeID;
            }
            set
            {
                this.m_EmployeeID = value;
            }
        }
        
        public virtual DateTime OrderDate
        {
            get
            {
                return this.m_OrderDate;
            }
            set
            {
                this.m_OrderDate = value;
            }
        }
        
        public virtual DateTime RequiredDate
        {
            get
            {
                return this.m_RequiredDate;
            }
            set
            {
                this.m_RequiredDate = value;
            }
        }
        
        public virtual DateTime ShippedDate
        {
            get
            {
                return this.m_ShippedDate;
            }
            set
            {
                this.m_ShippedDate = value;
            }
        }
        
        public virtual Int32 ShipVia
        {
            get
            {
                return this.m_ShipVia;
            }
            set
            {
                this.m_ShipVia = value;
            }
        }
        
        public virtual Decimal Freight
        {
            get
            {
                return this.m_Freight;
            }
            set
            {
                this.m_Freight = value;
            }
        }
        
        public virtual String ShipName
        {
            get
            {
                return this.m_ShipName;
            }
            set
            {
                this.m_ShipName = value;
            }
        }
        
        public virtual String ShipAddress
        {
            get
            {
                return this.m_ShipAddress;
            }
            set
            {
                this.m_ShipAddress = value;
            }
        }
        
        public virtual String ShipCity
        {
            get
            {
                return this.m_ShipCity;
            }
            set
            {
                this.m_ShipCity = value;
            }
        }
        
        public virtual String ShipRegion
        {
            get
            {
                return this.m_ShipRegion;
            }
            set
            {
                this.m_ShipRegion = value;
            }
        }
        
        public virtual String ShipPostalCode
        {
            get
            {
                return this.m_ShipPostalCode;
            }
            set
            {
                this.m_ShipPostalCode = value;
            }
        }
        
        public virtual String ShipCountry
        {
            get
            {
                return this.m_ShipCountry;
            }
            set
            {
                this.m_ShipCountry = value;
            }
        }
    }
}
